### ISSUE TITLE
Color picking in inline-edit branch

### ISSUE THREAD

**Issue by alexpreynolds** [alexpreynolds/cubemaker#9]
Changing a subcategory color only updates the color of one datapoint in the application data object. All datapoints that are members of the subcategory should have their color updated.

**Comment by natalia-zolochevska** [comment]
Fixed in color_picker_issue_9 branch

**Comment by alexpreynolds** [comment]
Applied color_picker_issue_9 patches to gh-pages branch in commit a84780f
